remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

# Setup
title: "Eva Price Demo Site"     
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: http://evapricedemo.com/download.zip
  another_url: another value

title:  "Eva Price Demo Site"             
tagline:  The Power of Digital Influence: How Social Media Strategies Have Impacted Coachella         
description:         
url:     http://eng470-s23.github.io          
baseurl:   /evapricedemo/            
