remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: ["Eva Price Demo Site"]
description: [The Power of Digital Influence: How Social Media Strategies Have Impacted Coachella   ]

github:
  zip_url: http://evapricedemo.com/download.zip
  another_url: another value
      
url:     http://eng470-s23.github.io          
baseurl:   /evapricedemo/            
